#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=pmhc_8k_xray_egnn
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --time=00:05:00
#SBATCH --output=../Outs/BS60_fast8.out

module purge
module load 2023
module load Anaconda3/2023.07-2

source activate mol

cd $HOME/ECGDM/
srun python -u Experiments/Structure_prediction/test.py --config Experiments/Structure_prediction/configs/pmhc_8K_xray_aligned_egnn.yml