#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=pmhc_8k_xray_egnn
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --time=05:00:00
#SBATCH --output=../outs/train_outs_new/pmhc_8k_xray_egnn.out

module purge
module load 2023
module load Anaconda3/2023.07-2

source activate mol

cd $HOME/MHC-Diff/
srun python -u train.py --config /gpfs/home4/dfruhbus/MHC-Diff/configs/new_config.yml